package com.hackathon.interview.dto;

import java.util.List;

/**
 * Structured feedback returned with the final response (REST contract shape).
 * Generated by Radhika's FeedbackService, not the engine.
 */
public record Feedback(String summary, List<String> strengths, List<String> gaps, List<String> next) {
}
